### ISSUE TITLE
Return Result from facade.global_context()

### ISSUE THREAD

**Issue by shellforge** [warpforge/warpgrapher#58]
Instead for returning an option, consider returning a result with the error GlobalContextNotFound when attempting to access the global_context from an engine that was built without a context. This will make accessing the global context a little more ergonomic with the `?` operator:

```
let global_context = facade.global_context()?;
```

**Comment by maldrake** [comment]
But is it an error to not have a global context?  Isn't it acceptable to not have one if you don't need it?  Or is the idea that it's an error to ask for one if it doesn't exist?

**Comment by shellforge** [comment]
Yes - the idea would be that asking for a GlobalContext on an engine where you did not configure one is an error.
